include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "ubuntu"
    SSH_HOST: "192.0.0.1"
    SSH_PRIVATE_KEY_BASE64: "$SSH_PRIVATE_KEY_BASE64"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 80:80"
