include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

#.docker_compose_run:
#  extends: .ssh
#  stage: deploy
#  variables:
#    OPT_DOCKER: ""
#    DOCKERFILE_PATH: Dockerfile
#    IMAGE_TAG: $CI_COMMIT_SHA
#    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#    DOCKER_HOST: tcp://docker:2376
#    DOCKER_TLS_CERTDIR: "/certs"
#    DOCKER_TLS_VERIFY: 1
#    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
#    DOCKER_DRIVER: overlay2
#    PRUNE_COMMAND: "docker system prune -f -a"
#    CONTAINER_NAME_SUFFIX: ""

 # script:
 #   - ssh $SSH_ADDRESS "mkdir /prod"
 #   - scp -r . $SSH_ADDRESS:home/prod
 #   - ssh $SSH_ADDRESS "cd home/prod && \ docker-compose down && \ docker-compose pull && \ docker-compose up -d"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 80:80"
