include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"
    POSTGRES_DATABASE: "$POSTGRES_DATABASE"
    POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    POSTGRES_USERNAME: "$POSTGRES_USERNAME"

.docker_compose_run:
  before_script:
    - apt-get update && apt-get install -y openssh-client
  script:
    - ssh $SSH_ADDRESS "mkdir /prod"
    - scp -r . $SSH_ADDRESS:home/prod
    - ssh $SSH_ADDRESS "cd home/prod && \ docker-compose down && \ docker-compose pull && \ docker-compose up -d"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_compose_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 8080:8080"
