include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "ubuntu"
    SSH_HOST: "prod-team-35-lg7sic6v.final.prodcontest.ru"
    SSH_PRIVATE_KEY_BASE64: "$SSH_PRIVATE_KEY_BASE64"

.docker_compose_run:
  extends: .ssh
  stage: deploy
  variables:
    OPT_DOCKER: ""
    DOCKERFILE_PATH: Dockerfile
    IMAGE_TAG: $CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_DRIVER: overlay2
    PRUNE_COMMAND: "docker system prune -f -a"
    CONTAINER_NAME_SUFFIX: ""
    POSTGRES_USERNAME: $POSTGRES_USERNAME
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DATABASE: $POSTGRES_DATABASE
    POSTGRES_CONN: "postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DATABASE"
  script:
    - AUTH_COMMAND="echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin"
    - ssh $SSH_ADDRESS "$AUTH_COMMAND"
    - ssh $SSH_ADDRESS "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - ssh $SSH_ADDRESS "mkdir -p /home/ubuntu/$CI_PROJECT_NAME"
    - scp docker-compose.yml $SSH_ADDRESS:/home/ubuntu/$CI_PROJECT_NAME/docker-compose.yml
    - ssh $SSH_ADDRESS "cd /home/ubuntu/$CI_PROJECT_NAME && echo 'IMAGE_NAME=$IMAGE_NAME' > .env  
        && echo 'POSTGRES_DATABASE=$POSTGRES_DATABASE' >> .env 
        && echo 'POSTGRES_USERNAME=$POSTGRES_USERNAME' >> .env 
        && echo 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD' >> .env 
        && echo 'POSTGRES_CONN=$POSTGRES_CONN' >> .env
        && echo 'RANDOM_SECRET=$RANDOM_SECRET' >> .env
        && echo 'SMTP_PASSWORD=$SMTP_PASSWORD' >> .env"
    - ssh $SSH_ADDRESS "cd /home/ubuntu/$CI_PROJECT_NAME && docker compose down || true"
    - ssh $SSH_ADDRESS "cd /home/ubuntu/$CI_PROJECT_NAME && docker compose up -d"
    - sleep 10
    - ssh $SSH_ADDRESS "cd /home/ubuntu/$CI_PROJECT_NAME && docker compose logs > /tmp/docker-compose.log"
    - scp $SSH_ADDRESS:/tmp/docker-compose.log ./docker-compose.log

  artifacts:

    paths:
      - docker-compose.log

.heltchcheck:
  stage: heltchcheck
  script:
    - pass
    -
stages:
  - build
  - deploy
  - heltchcheck

heltchcheck:
  stage: heltchcheck
  extends:
     - .heltchcheck

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_compose_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 443:443"
