include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
c2gtZWQyNTUxOQAAACB7ZJOwsn/44+KQ5uHM8wrD+OADyYVIThkP4TV6EaD0+gAA
AIjFIs/7xSLP+wAAAAtzc2gtZWQyNTUxOQAAACB7ZJOwsn/44+KQ5uHM8wrD+OAD
yYVIThkP4TV6EaD0+gAAAEAxkKav7qsIv0zStsDuOL7NFFBJFQshlG6t3iTXgdyV
z3tkk7Cyf/jj4pDm4czzCsP44APJhUhOGQ/hNXoRoPT6AAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----
"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  variables:
    OPT_DOCKER: "-p 80:80"
