services:
  api:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}

    volumes:
      - /home/ubuntu/ssl/cert.pem:/api/ssl/cert.pem
      - /home/ubuntu/ssl/fullchain.pem:/api/ssl/fullchain.pem

    ports:
      - "80:80"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432"