services:
  api:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

    volumes:
      - /home/ubuntu/ssl/cert.pem:/api/ssl/cert.pem
      - /home/ubuntu/ssl/privkey.pem:/api/ssl/privkey.pem

    ports:
      - "443:443"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432"

  postfix:
    image: catatnight/postfix
    container_name: postfix
    environment:
      maildomain: prod-team-35-lg7sic6v.final.prodcontest.ru
      smtp_user: MFS:${SMTP_PASSWORD}
    ports:
      - "25:25"
