services:
  api:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

    volumes:
      - /home/ubuntu/ssl/cert.pem:/api/ssl/cert.pem
      - /home/ubuntu/ssl/privkey.pem:/api/ssl/privkey.pem

    ports:
      - "443:443"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      SMTP_USER: ${SMTP_PASSWORD}
    ports:
      - "5432"

  postfix:
    image: boky/postfix:latest
    environment:
      - maildomain=prod-team-35-lg7sic6v.final.prodcontest.ru
      - smtp_user=MFS:${SMTP_PASSWORD}
      - relayhost=[smtp.gmail.com]:587
      - MYNETWORKS=0.0.0.0/0
      - ALLOWED_SENDER_DOMAINS=prod-team-35-lg7sic6v.final.prodcontest.ru
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./postfix-data:/var/spool/postfix
    restart: always
