services:
  api:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}

    ports:
      - "80:80"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432"

  postfix:
    image: catatnight/postfix
    container_name: smtp-server
    environment:
      - maildomain=prod-team-35-lg7sic6v.final.prodcontest.ru
      - smtp_user=root:FFehslqz88!
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./data:/var/mail