services:
  api:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      REDIS_CONN: "redis:6380"

    volumes:
      - /home/ubuntu/ssl/cert.pem:/api/ssl/cert.pem
      - /home/ubuntu/ssl/privkey.pem:/api/ssl/privkey.pem

    ports:
      - "25"
      - "443:443"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432"

  redis:
    image: redis:latest
    ports:
      - "6380"
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--port", "6380"]

  haraka:
    image: haraka/haraka:latest
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./haraka/config:/home/ubuntu/haraka/config
      - ./haraka/logs:/home/ubuntu/haraka/logs
    environment:
      - HARAKA_USER=MFS
      - HARAKA_PASSWORD=${SMTP_PASSWORD}

volumes:
  redis_data: