services:
  api:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

  #web:
  #  build: ./web

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"