services:
  api:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      REDIS_CONN: "redis:6380"

    healthcheck:
      test: ["CMD", "curl -f https://prod-team-35-lg7sic6v.final.prodcontest.ru/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

    volumes:
      - /home/ubuntu/ssl/fullchain.pem:/api/ssl/chain.pem
      - /home/ubuntu/ssl/privkey.pem:/api/ssl/privkey.pem

    ports:
      - "25"
      - "443:443"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432"

  redis:
    image: redis:latest
    ports:
      - "6380"
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--port", "6380"]

  postfix:
    image: boky/postfix:latest
    environment:
      - maildomain=prod-team-35-lg7sic6v.final.prodcontest.ru:443
      - smtp_user=MFS:${SMTP_PASSWORD}
      - relayhost=[connect.smtp.bz]:2525
      - MYNETWORKS=0.0.0.0/0
      - ALLOWED_SENDER_DOMAINS=prod-team-35-lg7sic6v.final.prodcontest.ru
    ports:
      - "25:25"
      - "587:587"
      - "443"
      - "2525:2525"

volumes:
  redis_data: