from fastapi import APIRouter

from .admin_sign_up.admin_sign_in import admin_auth_sign_in_router
from .approve_request.approve_request import approve_router
from .create_mentor.create_mentor import create_menter_router
from .get_mentor_by_id.get_mentor_by_id import get_mentor_router
from .get_mentors_list.get_mentors_list import get_mentors_router
from .get_requests_list.get_requests_list import get_requests_router
from .get_user_by_id.get_user_by_id import get_user_router
from .get_users_list.get_users_list import get_users_router
from .is_admin.is_admin import is_admin_router
from .delete_mentor.delete_mentor import delete_mentor_router

admin_router = APIRouter(tags=["Admins"])

admin_router.include_router(admin_auth_sign_in_router)
admin_router.include_router(get_requests_router)
admin_router.include_router(get_mentor_router)
admin_router.include_router(get_mentors_router)
admin_router.include_router(approve_router)
admin_router.include_router(get_users_router)
admin_router.include_router(get_user_router)
admin_router.include_router(create_menter_router)
admin_router.include_router(is_admin_router)
admin_router.include_router(delete_mentor_router)